## Data Preprocessing

In [2]:
#Importing the libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


#Importing the dataset
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:,3].values
print (X)
print (y)


#Taking care of missing data
from sklearn.preprocessing import Imputer
imputer = Imputer(missing_values = 'NaN', strategy = 'mean', axis = 0)
imputer = imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

print (X)

#Encoding categorical data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X = LabelEncoder()
X[:, 0] = labelencoder_X.fit_transform(X[:, 0])

print (X)

onehotencoder = OneHotEncoder(categorical_features = [0])
X = onehotencoder.fit_transform(X).toarray()
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)


#Splitting into training and test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=0)


#Feature scaling
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)

[['US' 43.0 71000.0]
 ['UK' 28.0 48000.0]
 ['Japan' 30.0 54000.0]
 ['UK' 38.0 60000.0]
 ['Japan' 40.0 nan]
 ['US' 34.0 58000.0]
 ['UK' nan 53000.0]
 ['US' 46.0 79000.0]
 ['Japan' 50.0 83000.0]
 ['US' 37.0 66000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']
[['US' 43.0 71000.0]
 ['UK' 28.0 48000.0]
 ['Japan' 30.0 54000.0]
 ['UK' 38.0 60000.0]
 ['Japan' 40.0 63555.555555555555]
 ['US' 34.0 58000.0]
 ['UK' 38.44444444444444 53000.0]
 ['US' 46.0 79000.0]
 ['Japan' 50.0 83000.0]
 ['US' 37.0 66000.0]]
[[2 43.0 71000.0]
 [1 28.0 48000.0]
 [0 30.0 54000.0]
 [1 38.0 60000.0]
 [0 40.0 63555.555555555555]
 [2 34.0 58000.0]
 [1 38.44444444444444 53000.0]
 [2 46.0 79000.0]
 [0 50.0 83000.0]
 [2 37.0 66000.0]]


/home/krds-deepak/anaconda3/lib/python3.7/site-packages/sklearn/utils/deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)
/home/krds-deepak/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/home/krds-deepak/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:390: D